### ISSUE TITLE
(short feature description)

### ISSUE THREAD

**Issue by tomjfrog** [jfrog/setup-jfrog-cli#132]
### Is your feature request related to a problem? Please describe.

The feature request is not related to an operational problem with the tool.  It's a documentation enhancement.

### Describe the solution you'd like to see

There is an undocumented, and quite useful, input to the Action for the OIDC integration.  In the code, it's clear we can take in an input parameter called ` oidc-audience`.  I'd like to see this documented.  This is an important configuration option that can make implementing the OIDC configuration in the JFrog Platform much easier for users. 

```yaml
      - name: Install JFrog CLI
        uses: jfrog/setup-jfrog-cli@v3
        env:
          JF_URL: ${{ vars.JF_URL }}
        with:
          oidc-provider-name: ${{ env.JF_OIDC_PROVIDER_NAME }}
          oidc-audience: ${{ env.OIDC_AUDIENCE }}
```
