### ISSUE TITLE
Multiple GitHub Runners on self-hosted runner cause permission issue

### ISSUE THREAD

**Issue by fuch1m** [jfrog/setup-jfrog-cli#144]
### How can we help?

Hello,

I run multiple self-hosted GitHub runners (github-runner1 - github-runner4) on the same machine. When I run this action a folder is generated under /tmp/jfrog which can only be accessed by the runner which created it, but any follow up workflow runs using other runners cause a "Permission denied" error, because they can't access the directory as it was generated by github-runner2 in that specific example.

```
user@server:~$ ls -l /tmp/jfrog/
total 4
drwxr-xr-x 3 github-runner2 github-runner2 4096 Apr 30 08:45 builds
```

Is there some way to specify the location of that folder with some environment variable or any other way to allow multiple runners on the same machine?

This is my action

```
name: build_app

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Artifactory
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ vars.JF_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
      - name: Build App
        run: echo "app" > app
      - name: Upload App
        run: jfrog rt u app sw-generic/
```

**Comment by yahavi** [comment]
@fuch1m 
Thank you for using this Action.
You can specify the JFrog home directory location by using the JFROG_CLI_HOME_DIR environment variable:
```yml
jobs:
  build:
    runs-on: self-hosted
    env:
      JFROG_CLI_HOME_DIR: <unique directory>
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Artifactory
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ vars.JF_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
...
```

Please let me know if that helped.

**Comment by fuch1m** [comment]
@yahavi 

Thank you for your fast response. This variable works great for me.

Here is my adapted workflow.

```
name: build_app

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Set JFrog CLI Home Directory
        run: echo "JFROG_CLI_HOME_DIR=/tmp/$USER/jfrog" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Artifactory
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ vars.JF_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
      - name: Build App
        run: echo "app" > app
      - name: Upload App
        run: jfrog rt u app sw-generic/
```
