### ISSUE TITLE
Cleanup Errors even with disable-auto-build-publish set to true

### ISSUE THREAD

**Issue by JackCoplandGranta** [jfrog/setup-jfrog-cli#196]
### Describe the bug

https://github.com/jfrog/setup-jfrog-cli/pull/185 added an automatic build-add-git and build-publish in the post step. This started failing some of our builds (mostly because it assumes the root of your workspace is a git repo which is another issue if you care about using the auto-publish). we've disabled everywhere by using:
> disable-auto-build-publish: true

but we still see cleanup failures in some builds

### Current behavior

![image](https://github.com/user-attachments/assets/5fb4aae9-fe6f-4d33-9df2-9ee41aeb9546)

![image](https://github.com/user-attachments/assets/b63f3948-3ad6-4fc6-bfe8-2e7b2faba5c6)

### Reproduction steps

```
name: jfrog test
on:
  workflow_dispatch:

jobs:

  jfrog_test:
    name: jfrog test
    runs-on: [<Tags-For-Self-Hosted-Machine-That-Can-Reach-Artifactory>]
    steps:

      - uses: jfrog/setup-jfrog-cli@v4
        with:
          disable-auto-build-publish: true
        env:
          JF_URL: <URL>
          JF_USER: <USER>
          JF_PASSWORD: <PASSWORD>

      - name: download
        env:
          JFROG_CLI_OFFER_CONFIG: "false"
        run: |
          jfrog rt dl <Path>/artifact.txt
        shell: pwsh
```

### Setup JFrog CLI version

4.3.1

### JFrog CLI version

2.66.0

### Workflow operating system type and version

Windows
