### ISSUE TITLE
Post setup-jfrog cleanup fails with v4.4.0 (works with v4.3.2)

### ISSUE THREAD

**Issue by anscfrisson** [jfrog/setup-jfrog-cli#206]
### Describe the bug

This bug appears in a private repository. This is the anonymized workflow:
```
...
- name: Setup Jfrog
        uses: jfrog/setup-jfrog-cli@v4
        env:
            JF_URL: ${{ env.ARTIFACTORY_URL }}
            JF_USER: ${{ secrets.ARTIFACTORY_USER }}
            JF_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
      - name: JFrog Ping
        # Returns OK if the connection is successful
        run: jf rt ping
      - name: Post artifact
        run: jf rt upload ${{ env.ARTIFACTORY_ARTIFACT }} ${{ env.ARTIFACTORY_PATH }}
```

- works if `uses: jfrog/setup-jfrog-cli@v4.3.2`
- fails at "Post Setup Jfrog" if `uses: jfrog/setup-jfrog-cli@v4.4.0`

### Current behavior

Fails at "Post Setup Jfrog" if `uses: jfrog/setup-jfrog-cli@v4.4.0`:
```
Post job cleanup.
Run '/home/runner/k8s/index.js'
Checking connection to JFrog Artifactory
Check for unpublished modules
Collect the Git information
Publish the build info to JFrog Artifactory
/__w/_actions/jfrog/setup-jfrog-cli/v4/node_modules/@actions/exec/lib/toolrunner.js:592
                error = new Error(`The process '${this.toolPath}' failed with exit code ${this.processExitCode}`);
                        ^

Error: The process '/__w/_tool/jf/2.66.0/x64/jf' failed with exit code 1
    at ExecState._setResult (/__w/_actions/jfrog/setup-jfrog-cli/v4/node_modules/@actions/exec/lib/toolrunner.js:592:25)
    at ExecState.CheckComplete (/__w/_actions/jfrog/setup-jfrog-cli/v4/node_modules/@actions/exec/lib/toolrunner.js:575:18)
    at ChildProcess.<anonymous> (/__w/_actions/jfrog/setup-jfrog-cli/v4/node_modules/@actions/exec/lib/toolrunner.js:469:27)
    at ChildProcess.emit (node:events:519:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)

Node.js v20.13.1
Error: Error: failed to run script step: command terminated with non-zero exit code: error executing command [sh -e /__w/_temp/386bb6d0-6b00-11ef-87d2-dd9b0dd8e501.sh], exit code 1
Error: Process completed with exit code 1.
Error: Executing the custom container implementation failed. Please contact your self hosted runner administrator.
```

### Setup JFrog CLI version

4.4.0

### JFrog CLI version

2.66.0

### Workflow operating system type and version

Ubuntu Jammy

**Comment by EyalDelarea** [comment]
Hey @anscfrisson,

Thank you for reporting this issue.

I attempted to reproduce the error on a private repository, but I was unable to replicate it.

We recently released version `v4.4.1`, which includes an updated CLI and additional logging. Could you please try updating and share the output again?

Also, does your workflow contain additional JFrog commands that you’re unable to share with us?

The more details you can provide, the better we’ll be able to identify and resolve the issue.

**Comment by AlexanderDavydov1** [comment]
I have the same issue. It started from today

**Comment by EyalDelarea** [comment]
> I have the same issue. It started from today

Hi @AlexanderDavydov1,
Are you also using a private repo with a self-hosted runner? If possible, could you share some details from your workflow and logs?
Thanks!

**Comment by AlexanderDavydov1** [comment]
> Are you also using a private repo with a self-hosted runner?
Yes, but change to v4.4.1 fixed issue

**Comment by EyalDelarea** [comment]
> > Are you also using a private repo with a self-hosted runner?
> > Yes, but change to v4.4.1 fixed issue

Happy to hear that!
@anscfrisson can you confirm that updating to 4.4.1 fixed the issue for you too?

**Comment by EyalDelarea** [comment]
@AlexanderDavydov1 and @anscfrisson,
Could you please review the post-action logs to confirm that there are no errors after the update? It would be helpful if you could share them here so we can ensure the issue doesn't reoccur.

Thank you!

**Comment by anscfrisson** [comment]
@EyalDelarea

Using `jfrog/setup-jfrog-cli@v4.4.1` or `jfrog/setup-jfrog-cli@master` (at b9a85a8d) both fail at
```
- name: Setup Jfrog
        uses: jfrog/setup-jfrog-cli@...
        env:
            JF_URL: ${{ env.ARTIFACTORY_URL }}
            JF_USER: ${{ secrets.ARTIFACTORY_USER }}
            JF_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
```
with:
```
  Downloading JFrog CLI from https://releases.jfrog.io/artifactory/jfrog-cli/v2/2.67.0/jfrog-cli-linux-amd64/jfrog
  /__w/_tool/jf/2.67.0/x64/jf config add setup-jfrog-cli-server --url *** --interactive=false --overwrite=true --user *** --password ***
  15:21:47 [Info] Trace ID for JFrog Platform logs: 592b4c36b2aa783b
  Error: 7 [Error] The following error was received while trying to encrypt your password: Artifactory response: 401 
  {
    "errors": [
      {
        "status": 401,
        "message": "Bad credentials"
      }
    ]
  } 
  Error: The process '/__w/_tool/jf/2.67.0/x64/jf' failed with exit code 1
```
Reverting back to `jfrog/setup-jfrog-cli@v4.3.2` works again with:
```
Setup JFrog CLI
  Downloading JFrog CLI from https://releases.jfrog.io/artifactory/jfrog-cli/v2/2.66.0/jfrog-cli-linux-amd64/jfrog
  /__w/_tool/jf/2.66.0/x64/jf config add setup-jfrog-cli-server --url *** --interactive=false --overwrite=true --user *** --password ***
  16:12:01 [Warn] You are using JFrog CLI version 2.66.0, however version 2.67.0 is available.
  To install the latest version, visit: https://jfrog.com/getcli
  To see the release notes, visit: https://github.com/jfrog/jfrog-cli/releases
  To avoid this message, set the JFROG_CLI_AVOID_NEW_VERSION_WARNING variable to TRUE
```

The problem seems to be with JFrog CLI version updates between 2.66.0 and 2.67.0.

From https://github.com/jfrog/jfrog-cli/compare/v2.66.0...v2.67.0:
```diff
-	github.com/jfrog/jfrog-cli-core/v2 v2.55.6
+	github.com/jfrog/jfrog-cli-core/v2 v2.55.7
-	github.com/jfrog/jfrog-cli-security v1.7.2
+	github.com/jfrog/jfrog-cli-security v1.8.0
```
- https://github.com/jfrog/jfrog-cli-core/compare/v2.55.6...v2.55.7
- https://github.com/jfrog/jfrog-cli-security/compare/v1.7.2...v1.8.0

Might this `401` issue be due to updates of jfrog-cli(-core|-security)?
