### ISSUE TITLE
OIDC-only mode that doesn’t install jfrog CLI

### ISSUE THREAD

**Issue by pavelzw** [jfrog/setup-jfrog-cli#209]
### Is your feature request related to a problem? Please describe.

We are using this action to authenticate with OIDC to jfrog’s servers.
We don’t use jfrogs cli tools but our own tooling (docker, conda, pixi, …)
Would it be possible to skip the download + configure cli parts and _only_ do the OIDC auth in this action?

### Describe the solution you'd like to see

```yml
- uses: jfrog/setup-jfrog-cli@v4
  with:
    oidc-provider-name: ${{ vars.ARTIFACTORY_OIDC_PROVIDER }}
    oidc-audience: ${{ vars.ARTIFACTORY_OIDC_AUDIENCE }}
    oidc-only: true
  env:
    JF_URL: ${{ vars.ARTIFACTORY_URL }}
- uses: prefix-dev/setup-pixi@v0.8.1
  with:
    auth-host: ${{ vars.ARTIFACTORY_URL }}
    auth-username: ${{ steps.artifactory.outputs.oidc-user }}
    auth-password: ${{ steps.artifactory.outputs.oidc-token }}
```
