### ISSUE TITLE
Capability to set a custom server id

### ISSUE THREAD

**Issue by EricDales** [jfrog/setup-jfrog-cli#214]
### Is your feature request related to a problem? Please describe.

Hello, 

- I want to add the .jfrog/projects/maven.yaml to my git repo so the configuration is automatically shared with my team. 
- To make it usable in a GitHub Actions workflow, server id in .jfrog/projects/maven.yaml must be the same as the one in ~/.jfrog/jfrog-cli.conf.v6
- setup-jfrog-cli forces the server id to be setup-jfrog-cli-server which is not meaningful to me

### Describe the solution you'd like to see

I would like to be able to specify the server id as a setup-jfrog-cli parameter:

```yaml
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: https://${{ vars.JF_DNS }}/
          JF_USER: ${{ vars.JF_USER }}
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
          JF_SERVER_ID: ${{ vars.JF_SERVER_ID}}
```

### Describe alternatives you've considered

- Adding a jf add command in my workflow: it defeats the benefit of setup-jfrog-cli to have a single configuration step

### Additional context

Already commented in #86
