### ISSUE TITLE
Permission denied on install despite manually setting home and temp dir env vars

### ISSUE THREAD

**Issue by austinhallett** [jfrog/setup-jfrog-cli#222]
### Describe the bug

Looks like the install fails on self-hosted runner. Attempted the fix suggested in this issue https://github.com/jfrog/setup-jfrog-cli/issues/144 to no avail
```
  - 
    id: setup-jf
    name: Setup JFrog CLI
    uses: jfrog/setup-jfrog-cli@v3
    env:  
      JF_URL: ${{ vars.ARTIFACTORY_URL }}
      JFROG_CLI_HOME_DIR: $HOME/.jfrog
      JFROG_CLI_TEMP_DIR: $HOME/.jfrog/tmp
    with:
      oidc-audience: ${{ env.OIDC_AUDIENCE }}
      oidc-provider-name: ${{ env.OIDC_PROVIDER }}
...
```

### Current behavior

```
Setup JFrog CLI
  Obtaining an access token through OpenID Connect...
  Downloading JFrog CLI from https://releases.jfrog.io/artifactory/jfrog-cli/v2/2.52.9/jfrog-cli-linux-amd64/jfrog
  Error: EACCES: permission denied, mkdir '/__t/jf'
```

### Setup JFrog CLI version

@v3

### JFrog CLI version

2.52.9

### Workflow operating system type and version

Ubuntu 22.04
