### ISSUE TITLE
Breaking change in latest setup-jfrog release without changing major version

### ISSUE THREAD

**Issue by mcurole** [jfrog/setup-jfrog-cli#268]
### Describe the bug

The latest release for `setup-jfrog` kept the major version for the release at `v4`. This version took away the ability to download the CLI through a remote repository using OIDC. All of our OIDC workflows broke overnight because they could no longer download the JFrog cli. 

### Current behavior

![Image](https://github.com/user-attachments/assets/65643163-8535-44a4-9ea7-1413d0ac703c)

### Reproduction steps

Configure an action to use OIDC to authenticate and include the download-repository variable.

```yaml
      - uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ vars.JF_URL }}
        with:
          download-repository: jfrog-cli
          oidc-provider-name: github
          oidc-audience: jfrog-github
```

### Expected behavior

I would expect the workflow to download the cli using OIDC and then continue to run.

### Setup JFrog CLI version

v4 and v4.5.9

### JFrog CLI version

latest

### Workflow operating system type and version

ubuntu 24.04

### JFrog Artifactory version (if relevant)

Artifactory 7.112.0 Cloud
