### ISSUE TITLE
latest v4 tag breaks OIDC

### ISSUE THREAD

**Issue by mahngiel** [jfrog/setup-jfrog-cli#270]
### Describe the bug

The latest version of the action breaks OIDC. backporting to `@v4.5.6` restores function

### Current behavior

```sh
Run jfrog/setup-jfrog-cli@v4
Setup JFrog CLI
  Downloading JFrog CLI from https://releases.jfrog.io/artifactory/jfrog-cli/v2/2.75.0/jfrog-cli-linux-amd64/jfrog
  
  16:55:45 [Info] Trace ID for JFrog Platform logs: dc5ae0592ca87c28
  Error: 5 [Error] failed to exchange OIDC token: server response: 400 Bad Request
  {
    "errors": [
      {
        "code": "BAD_REQUEST",
        "message": "Invalid audience"
      }
    ]
  }
  
  Error: JFrog CLI exited with exit code 1
```

### Reproduction steps

use this
```yaml
  - uses: jfrog/setup-jfrog-cli@v4
      id: jfrog
      env:
          JF_URL: https://<myOrg>.jfrog.io
          JF_PROJECT: <myProject>
      with:
          oidc-provider-name: <providerName>
```

### Setup JFrog CLI version

v4

### JFrog CLI version

2.74.1

### Workflow operating system type and version

ubuntu-latest

### JFrog Artifactory version (if relevant)

cloud

**Comment by mahngiel** [comment]
after additional version testing, v4.5.8 also functions as expected
```yaml
    - uses: jfrog/setup-jfrog-cli@v4.5.6
      id: jfrog456
      if: always()
      env:
          JF_URL: https://<myOrg>.jfrog.io
          JF_PROJECT: <myProject>
      with:
          oidc-provider-name: github

    - uses: jfrog/setup-jfrog-cli@v4.5.7
      id: jfrog457
      if: always()
      env:
          JF_URL: https://<myOrg>.jfrog.io
          JF_PROJECT: <myProject>
      with:
          oidc-provider-name: github

    - uses: jfrog/setup-jfrog-cli@v4.5.8
      id: jfrog458
      if: always()
      env:
          JF_URL: https://<myOrg>.jfrog.io
          JF_PROJECT: <myProject>
      with:
          oidc-provider-name: github

    - uses: jfrog/setup-jfrog-cli@v4.5.9
      id: jfrog459
      if: always()
      env:
          JF_URL: https://<myOrg>.jfrog.io
          JF_PROJECT: <myProject>
      with:
          oidc-provider-name: github

    - uses: jfrog/setup-jfrog-cli@v4.5.10
      id: jfrog4510
      if: always()
      env:
          JF_URL: https://<myOrg>.jfrog.io
          JF_PROJECT: <myProject>
      with:
          oidc-provider-name: github
```


```sh
2s
Run jfrog/setup-jfrog-cli@v4.5.6
  
Setup JFrog CLI
  Obtaining an access token through OpenID Connect...
  Config file is empty or not found.
  Downloading JFrog CLI from https://releases.jfrog.io/artifactory/jfrog-cli/v2/2.73.0/jfrog-cli-linux-amd64/jfrog
  /opt/hostedtoolcache/jf/2.73.0/x64/jf config add setup-jfrog-cli-server --url https://idexxlabs.jfrog.io/ --interactive=false --overwrite=true --access-token ***
  18:24:36 [Warn] You are using JFrog CLI version 2.73.0, however version 2.75.0 is available.
  To install the latest version, visit: https://jfrog.com/getcli
  To see the release notes, visit: https://github.com/jfrog/jfrog-cli/releases
  To avoid this message, set the JFROG_CLI_AVOID_NEW_VERSION_WARNING variable to TRUE
  
1s
Run jfrog/setup-jfrog-cli@v4.5.7
  
Setup JFrog CLI
  Downloading JFrog CLI from https://releases.jfrog.io/artifactory/jfrog-cli/v2/2.75.0/jfrog-cli-linux-amd64/jfrog
  /opt/hostedtoolcache/jf/2.75.0/x64/jf config add setup-jfrog-cli-server --url https://idexxlabs.jfrog.io/ --interactive=false --overwrite=true --oidc-provider-name=github --oidc-provider-type=Github --oidc-token-id=*** --oidc-audience=jfrog-github
  18:24:38 [Info] Trace ID for JFrog Platform logs: 5abe5e2520cf4610
  Error: 8 [Error] failed to exchange OIDC token: server response: 400 Bad Request
  {
    "errors": [
      {
        "code": "BAD_REQUEST",
        "message": "Invalid audience"
      }
    ]
  }
  Error: JFrog CLI exited with exit code: 1
  
1s
Run jfrog/setup-jfrog-cli@v4.5.8
Setup JFrog CLI
  Config file is empty or not found.
  Downloading JFrog CLI from https://releases.jfrog.io/artifactory/jfrog-cli/v2/2.74.1/jfrog-cli-linux-amd64/jfrog
  /opt/hostedtoolcache/jf/2.74.1/x64/jf config add setup-jfrog-cli-server --url https://idexxlabs.jfrog.io/ --interactive=false --overwrite=true --access-token ***
  
1s
Run jfrog/setup-jfrog-cli@v4.5.9
Setup JFrog CLI
  Found JFrog CLI in cache. No need to download
  18:24:40 [Info] Trace ID for JFrog Platform logs: edc739f66a4af12e
  Error: 0 [Error] failed to exchange OIDC token: server response: 400 Bad Request
  {
    "errors": [
      {
        "code": "BAD_REQUEST",
        "message": "Invalid audience"
      }
    ]
  }
  Error: JFrog CLI exited with exit code 1
  
0s
Run jfrog/setup-jfrog-cli@v4.5.10
Setup JFrog CLI
  Found JFrog CLI in cache. No need to download
  18:24:40 [Info] Trace ID for JFrog Platform logs: 0e06a71aa5f7262f
  Error: 0 [Error] failed to exchange OIDC token: server response: 400 Bad Request
  {
    "errors": [
      {
        "code": "BAD_REQUEST",
        "message": "Invalid audience"
      }
    ]
  }
  Error: JFrog CLI exited with exit code 1

**Comment by EyalDelarea** [comment]
Hey @mahngiel,

Thank you for reporting this issue.
Could you please share the following information in order to allow us better debugging:

1. Debug logs for the latest version: `v4.5.10`
2. Which Artifactory version are you using?

**Comment by EyalDelarea** [comment]
Hey @mahngiel,

Thank you for the debug logs

It looks like the second example you provided is working — is that correct?

Also, have you tried providing the `audience` value in the action to match the audience defined in your integration?  
For example:

```yaml
- uses: jfrog/setup-jfrog-cli@v4
  env:
    JF_URL: https://<myOrg>.jfrog.io
    JF_PROJECT: <myProject>
  with:
    oidc-provider-name: github
    oidc-audience: my-audience
```
