### ISSUE TITLE
The PATH variable is not preserved after setup

### ISSUE THREAD

**Issue by Frujina** [jfrog/setup-jfrog-cli#276]
### Describe the bug

The directories which are on the PATH environment variable are removed after the call to the setup-jfrog-cli action. 

### Current behavior

```
      - name: Show PATH before 
        run: |
          export PATH="/home/user/uv/:$PATH"
          echo "path=$PATH" >>$GITHUB_ENV
          env

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@ff5cb544114ffc152db9cea1cd3d5978d5074946 # v4.5.11
        env:
          JF_URL: <URL>
          JF_USER: <USER>
          JF_PASSWORD: <PASS>
        with:
          disable-job-summary: true
          disable-auto-build-publish: true
          version: latest
      - name: SHOW PATH AFter
        run: |
          env
```

### Setup JFrog CLI version

4.5.11

### JFrog CLI version

2.75.1

### Workflow operating system type and version

Ubuntu 22.04
