### ISSUE TITLE
Why does the cleanup step take so long?

### ISSUE THREAD

**Issue by raihle** [jfrog/setup-jfrog-cli#277]
I have a pretty simple workflow that installs dependencies with `jf npm ci`. This leads to build info being published automatically, which is what I want (eventually I will also publish an artifact, but one thing at a time).

The build info is published as part of the cleanup (post) step at the end of the workflow, and that part finishes pretty quickly (within seconds). After this, my server config / credentials are deleted. For some reason, this last step (which should not be much more complicated than deleting a single file?) consistently takes _3 minutes_. Why? What can I do to avoid this?

Relevant workflow steps:

```yaml
      - name: Setup JFrog CLI with OIDC
        uses: jfrog/setup-jfrog-cli@v4
        id: jfrog_oidc
        env:
          JF_URL: ***
          JF_PROJECT: ***
        with:
          oidc-provider-name: ***
          oidc-audience: ***
          custom-server-id: xyz
          
      - name: Install dependencies
        run: jf npm ci
```

Example logs with timestamps:
> Tue, 03 Jun 2025 07:54:26 GMT ::group::Cleanup JFrog CLI servers configuration
> Tue, 03 Jun 2025 07:54:26 GMT Cleanup JFrog CLI servers configuration
> Tue, 03 Jun 2025 07:54:26 GMT   The value of custom is: 'xyz'
> Tue, 03 Jun 2025 07:54:26 GMT   ##[debug]Removing custom server ID: 'xyz'...
> Tue, 03 Jun 2025 07:54:26 GMT   /home/runner/_work/_tool/jf/2.75.0/x64/jf c rm xyz --quiet
> Tue, 03 Jun 2025 07:54:26 GMT   ::endgroup::
> Tue, 03 Jun 2025 07:57:26 GMT ##[debug]Node Action run completed with exit code 0
> Tue, 03 Jun 2025 07:57:26 GMT ##[debug]JFROG_CLI_COMMAND_SUMMARY_OUTPUT_DIR=''
> Tue, 03 Jun 2025 07:57:26 GMT ##[debug]JFROG_CLI_COMMAND_SUMMARY_OUTPUT_DIR='/home/runner/_work/_temp'
> Tue, 03 Jun 2025 07:57:26 GMT ##[debug]JFROG_CLI_USAGE_AUTO_BUILD_PUBLISHED='TRUE'
> Tue, 03 Jun 2025 07:57:26 GMT ##[debug]Finishing: Post Setup JFrog CLI with OIDC
