### ISSUE TITLE
Unwanted config created if oidc-provider-name is set empty

### ISSUE THREAD

**Issue by neatcoder** [jfrog/setup-jfrog-cli#281]
### Describe the bug

When the action is called with an empty value set in oidc-provider-name, it creates a dummy config.
```yaml 
- name: Setup JFrog
  uses: jfrog/setup-jfrog-cli@ff5cb544114ffc152db9cea1cd3d5978d5074946
  env:
    JF_ENV_1: ${{ steps.check-token.outputs.jf-env-1 }}
    JF_URL: "https://xyz.jfrog.io"
  with:
    oidc-provider-name: ${{ inputs.oidc-provider-name }}
```

![Image](https://github.com/user-attachments/assets/988cf9d1-93b6-4fa3-8c76-8641c91b7330)

### Current behavior

Action creates an unwanted config when supplied with an empty `oidc-provider-name` input

### Expected behavior

Action should ignore creating a config if an empty value is provided in `oidc-provider-name` input

### Setup JFrog CLI version

4.5.11

### JFrog CLI version

2.77.0

### Workflow operating system type and version

ubuntu-latest
