### ISSUE TITLE
Task leaks credentials to other jobs

### ISSUE THREAD

**Issue by wichert** [jfrog/setup-jfrog-cli#32]
**Describe the bug**
This tasks configured jfrog, but never cleans up credentials after the job is finished. This results in credentials leaking to other workflows that are running on the same GitHub runner if they share the homedirectory, which is a common (required?) configuration for runners in GitHub Enterprise environments.

**To Reproduce**

1. Create a workflow that uses `jfrog/setup-cfrog-cli@v1`
2. Run the workflow
3. See that `~/.jfrog/jfrog-cli.conf.v4` still exists after the job has finished, or already exists when you run the same job again.

Please note that this is **not** reproducible on github.com, since they reset the homedirectory for every job.

**Expected behavior**

I expect the action to have a `post` script that removes all jfrog credentials

**Versions**
- Setup JFrog CLI version: current master
- Workflow operating system: Ubuntu
- JFrog CLI version:  1.44
- Artifactory Version: all

**Comment by yahavi** [comment]
@wichert,
Thanks for reporting this issue.
The Setup JFrog CLI GitHub Action downloads the JFrog CLI and configures the JFrog connection details under `$USER_HOME/.jfrog/`. The credentials will be available to all next JFrog CLI commands.
The Action can't have a `post` script, since the JFrog CLI commands run after this Action.
Therefore, for self-hosted agents, we'd recommend to configure a cleanup step:
```yml
# Run the action
- jfrog/setup-jfrog-cli@v1
  env:
  JF_ARTIFACTORY_1: ${{ secrets.JF_ARTIFACTORY_SECRET_1 }}
# Run CLI commands 
- run: |
   jfrog rt ...

...

# Clean up at the end of the workflow
- name: Clean Up
   if: ${{ always() }}
   run: jfrog c rm --quiet
```
Please let us know if that helped.
