### ISSUE TITLE
What type of repository should I setup in Artifactory to use this action?

### ISSUE THREAD

**Issue by callum-tait-pbx** [jfrog/setup-jfrog-cli#37]

**Comment by yahavi** [comment]
@callum-tait-pbx,
Can you please elaborate more about your use case?

**Comment by callum-tait-pbx** [comment]
Just starting to look at using this with our Artifactory. We want to use Artifactory to be able to upload a build in 1 job and in a downstream job download the build again. We don't want to upload to Github's servers al la:

https://github.com/actions/upload-artifact
https://github.com/actions/download-artifact

I've setup a generic repository as I think that is right. I am a little confused how to use this though, we use your saas product, I as expecting to have ot provide an API key and an endpoint to authenticate? I alread have an API key generated but the docs are written as if you make one via action and then put that in your secrets?

**Comment by yahavi** [comment]
@callum-tait-pbx,
Using the JFrog CLI, you can upload and download artifacts from all repository types, including generic ones.
This Action downloads, installs, and configures the JFrog CLI in your workflow.

To use this action, please follow the following steps:
1. Download JFrog CLI to your local machine https://jfrog.com/getcli/.
2. Configure your Artifactory server in your local machine by running `jfrog config add`.
3. Create a server token: `jfrog config export`. This token contains all of the required server details - Artifactory URL, API key, etc.
4. In your GitHub repository under `Settings`/`Secrets`, create a secret `JF_ARTIFACTORY_SECRET_1` and fill it with your server token (requires admin privileges in your GitHub repository).
5. Use this action:
```yml
- uses: jfrog/setup-jfrog-cli@v1
  env:
    JF_ARTIFACTORY_1: ${{ secrets.JF_ARTIFACTORY_SECRET_1 }}
- run: |
    # Upload
    jfrog rt upload <path to a file> <full path in Artifactory>

    # Download
    jfrog rt download <full path in Artifactory> <path to download>
```

Read more:
* [Usage](https://github.com/jfrog/setup-jfrog-cli#usage)
* [JFrog CLI upload](https://www.jfrog.com/confluence/display/CLI/CLI+for+JFrog+Artifactory#CLIforJFrogArtifactory-UploadingFiles)
* [JFrog CLI download](https://www.jfrog.com/confluence/display/CLI/CLI+for+JFrog+Artifactory#CLIforJFrogArtifactory-DownloadingFiles)

Please let us know if you need any further assistance.
