### ISSUE TITLE
Using jfrog/setup-jfrog-cli with flexible customization in a controlled environment

### ISSUE THREAD

**Issue by leowangms** [jfrog/setup-jfrog-cli#78]
**Is your feature request related to a problem? Please describe.**
jfrog/setup-jfrog-cli action supports getting connection details as secrets. However in a controlled corporate environment, users are not capable of generating required json string using provided command. It will be helpful if both remote host/repo/auth can be provide as action inputs.

**Describe the solution you'd like to see**

```
- uses: jfrog/setup-jfrog-cli@v2
  env:
    # The JFrog CLI will be downloaded from the configured Artifactory server in JF_ENV_1
    JF_ENV_1: ${{ secrets.JF_SECRET_ENV_1 }}
  with:
    download-repository: jfrog-cli-remote
    download-host: https://[own jfrog host]
   download-auth-access-token: ${{ secrets.JF_ACCESS_TOKEN }}
     or 
   download-auth-basic: ${{ secrets.JF_BASIC_AUTH }}
```

**Describe alternatives you've considered**
One alternative is to fork and make the change ourselves, but we'd prefer to use the public action. We suspect there are others with similar requirements who would benefit from this.

**Additional context**
Basic auth and access token are mutually exclusive. Only one is required.
